### ISSUE TITLE
Coordinate systems

### ISSUE THREAD

**Issue by montalb** [jeffwalton/photogrammetry-resection#1]
Is there any specific coordinate system that should be used for the ground point coordinates?

**Comment by JeffWalton-PSC** [comment]
It can be any arbitrary Cartesian system with the origin at the Earth's center of mass or a local topocentric system.

From "Introduction to Modern Photogrammetry" (Mkihail, Bethel, and McGlone; 2001):
![image](https://user-images.githubusercontent.com/37444379/95760663-4c8fca00-0c79-11eb-9187-2b6873b1f07b.png)
![image](https://user-images.githubusercontent.com/37444379/95760765-6b8e5c00-0c79-11eb-8984-72aa22c19366.png)
